apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
  labels:
    app: stress
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9100"
spec:
  containers:
    - name: stress
      image: progrium/stress
      command: ["stress"]
      args: ["--cpu", "2", "--timeout", "300s"]
    - name: node-exporter
      image: prom/node-exporter
      ports:
        - containerPort: 9100
      args:
        - "--path.rootfs=/host"
      volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host
          readOnly: true
  volumes:
    - name: proc
      hostPath:
        path: /proc
    - name: sys
      hostPath:
        path: /sys
    - name: root
      hostPath:
        path: /
